### PR TITLE
adds soft-deleting functionality

### PR DESCRIPTION
**Pull request by sethcwhiting**
My team needs the ability to non-destructively delete data, so I added this in my forked copy. I figured other people may benefit from the same functionality.

### CODE REVIEW

**Comment by RWOverdijk** [comment]
You can best add this functionality in your own app. Add a default filter (collectionQuery for example) that filters out "deleted" items, and create your own delete method in your dataprovider that doesn't actually delete, but updates with the soft delete flag set.

Nice to see contributions, but this gets a -1 from me, sorry.

**Comment by sethcwhiting** [comment]
@RWOverdijk Thanks for the review & reply!

My question is: If you were getting started on a project and you knew your team wanted soft deleting functionality (I know many do), would you rather do it the way you described, or by simply setting the option to "true" and moving on?

I'm just trying to make a very common thing quicker and easier for everyone after me in my same position.

**Comment by RWOverdijk** [comment]
Honestly? I would rather do it myself. But my opinion on that point is irrelevant. I would argue that this feature is an upstream architectural decision (in other words, react admin) and does not belong in an adapter such as this one.

Besides, implementing what I suggested takes very little work and the feature as proposed is not as common as you might think. What if I only want to enable this for some resources? What if I want to conditionally soft delete things? What if I want to soft delete once, and then do an actual delete?

All of these could be flags. But at some point you have to draw the line and just implement the logic specific to what you need.

My suggestion is to instead make this a "recipe". Create some guides for the adapter that provide some solutions for common challenges. By showing others how this could be implemented you also hand them the tools to add whatever logic it is they need for their specific use cases. You have the right idea, and I don't mean to shit on your efforts (not at all!), but I don't think this is the right approach. I even think the metadata flag that Ben implemented is a bad idea (sorry Ben, still love you ❤️).

If you don't like the idea of recipes, you could even make a package yourself and implement these things as utilities. Call them feature-patches or something?

```js
import { FirebaseDataProvider } from 'react-admin-firebase';
import { featurePatch, softDelete } from 'ra-firebase-feature-patch';

/* ... */

// Some resources
<Admin dataProvider={featurePatch(dataProvider, softDelete(['resourceName']))} />

// All resources
<Admin dataProvider={featurePatch(dataProvider, softDelete())} />
```

That way you can add other cool patchers such as cloudinary file uploads or logging hooks.

**Comment by benwinding** [comment]
Hey @sethcwhiting and @RWOverdijk,

Firstly, both of you have valid arguments which makes it hard to decide which way to take this.

**Simple**
On the one hand we want to keep the library simple, easy to use and easy to maintain. Anything that's not essential should not really be included within this library. This makes for a better architecture overall and closely follows the [unix philosophy](https://homepage.cs.uri.edu/~thenry/resources/unix_art/ch01s06.html) and is [pretty common in npm development](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328).

**Monolithic**
On the other hand this is a monolithic library which opposes the _simple_ view point of other smaller libraries. This library, just like react-admin has many different responsibilities; `Dataprovider`, `Authentication`, `Login` etc..

The real purpose of `react-admin` and as a result _this library_ is to simplify and reduce the amount of boilerplate code required to get something working. Which is why config flags for common functions like `metadata` and `softdelete` are a good feature to include in this situation. 

There are a lot of examples of seemingly simple applications that have _smart defaults_ which help the end user tremendously a few I can think of are:
- FFMpeg
- Youtube downloader
- Git

**Protecting against bloat**
I agree @RWOverdijk, if we open the door to these flags, there could be many more flooding in, so we need a way to protect the library from overflowing with specific requests which don't really reflect everyone's needs.

> My suggestion is to instead make this a "recipe". Create some guides for the adapter that provide some solutions for common challenges. By showing others how this could be implemented you also hand them the tools to add whatever logic it is they need for their specific use cases.

``` js
import { FirebaseDataProvider } from 'react-admin-firebase';
import { featurePatch, softDelete } from 'ra-firebase-feature-patch';
/* ... */
// Some resources
<Admin dataProvider={featurePatch(dataProvider, softDelete(['resourceName']))} />
// All resources
<Admin dataProvider={featurePatch(dataProvider, softDelete())} />
```
But I think that's a great idea to implement, maybe we could encapsulate all _helper functions_ (or flags) into another library `react-admin-firebase-helpers` maybe? This could simplify this library too, but the tradeoff is managing 2 sets of libraries and keeping the API consistent and compatible between them.

**Conclusion**
@RWOverdijk I encourage you to work on the **recipe idea** that you mentioned and if you'd like to contribute another `helper` package or something to the project let me know. However to solve the problems now, I think config flags are pretty easy for the user, which makes them a good idea IMHO, so I'm going to merge in @sethcwhiting's changes.

Thanks for both of your input,
Ben

**Comment by RWOverdijk** [comment]
Sure man, All I did was -1 it 😄 We both know that I'm rewriting the whole lib first chance I get anyway.

**Pull request merged**
