### PR TITLE
react-admin 3.0 upgrade

### LINKED ISSUE #46: Update to React-Admin v3
React-Admin planning to release v3 this summer. Right now they are finalizing the alpha and started to preparing the migration guide.
Are there any plans to start migrating this package to work with v3? I did a quick check yesterday and there are some breaking changes that will be impacting this package.

https://github.com/marmelab/react-admin/releases

Next branch: https://github.com/marmelab/react-admin/blob/next/UPGRADE.md

**TODOs**
- [x] Removed RA realtime as per https://github.com/marmelab/react-admin/pull/3908#issue-334448261
- [x] Implemented authProvider as object instead of function
- [x] authProvider.login method will now check for auth state change if no email and password is provided - enabling easy usage with third party Oauth firebase login flows (simply use useLogin without username and password **OR** specify '/' as the redirect URL as the checkAuth method will take care of making sure the user is logged in when redirecting)
- [x] Added example for usage with https://github.com/firebase/firebaseui-web-react resolves https://github.com/benwinding/react-admin-firebase/issues/34
- [x] Make react, react-admin and react-dom peerDependencies
- [x] Update demo project

Thanks to @simonberger (https://github.com/benwinding/react-admin-firebase/pull/67)

- [ ] Update docs

**Beta Version** 

We are getting closer to the stable version of this package which supports `react-admin` v3. Thanks to @simonbuerger he provided a pull request (https://github.com/benwinding/react-admin-firebase/pull/67) with the needed work.

To try the beta version of the package use the following to manually update the package in your project (for npm use `npm install`):
- update `react-admin` to the lastest version
-  `npm install` / `yarn add github:benwinding/react-admin-firebase#upgrade-to-react-admin-v3`

### PR DESCRIPTION
**Pull request by simonbuerger**
- [x] Removed RA realtime as per https://github.com/marmelab/react-admin/pull/3908#issue-334448261
- [x] Implemented authProvider as object instead of function
- [x] authProvider.login method will now check for auth state change if no email and password is provided - enabling easy usage with third party Oauth firebase login flows (simply use useLogin without username and password **OR** specify '/' as the redirect URL as the checkAuth method will take care of making sure the user is logged in when redirecting)
- [x] Added example for usage with https://github.com/firebase/firebaseui-web-react resolves https://github.com/benwinding/react-admin-firebase/issues/34
- [x] Make react, react-admin and react-dom peerDependencies
- [x] Update demo project
- [ ] Update docs

@benwinding Should I include the dist files in the PR?

Pity about ra-realtime, but does not look like it is supported any longer. A solution to that seems beyond the scope of this upgrade and like a separate task?

Resolves #46 #34

### CODE REVIEW

**Comment by benwinding** [comment]
Wow amazing work @simonbuerger!

Thank you for your contribution! I agree that the `ra-realtime` issue is a separate task we can deal with afterwards.

Everything seems to work pretty well. And thanks for implementing the FirebaseUI in issue #34. 

The only problem I found is that the login loader seems to be loading indefinitely as shown below, can you confirm this:

image

We'll need to merge it in before building the `dist` files and deploying too.

**Comment by simonbuerger** [comment]
@benwinding I'm actually not getting that - is it throwing any errors?

**Comment by simonbuerger** [comment]
Oh and should I submit a PR to update the example repos? Or do you take care of those?

**Comment by LaszloDev** [comment]
@benwinding can you please merge this into the `upgrade-to-react-admin-v3`-branch so we can continue to work on it together? An beta NPM package for it would be great too.

BTW Merry christmas

**Comment by LaszloDev** [comment]
Will do the preparation to merge it with the v3 repo branch as soon as I’m back at my laptop.

@benwinding what is the general strategy regard publishing the NPM package, I do see that you checked in the `/dist` folder. Is that necessary and can we configure Github actions to automatically publish on master merge? With this we might need to introduce a `dev` or `next`-branch for the pull requests to be merged to, check them and then only merge to master. 
I guess the versioning of the NPM package is done manually by you, before publishing?

**Comment by steurt** [comment]
> @benwinding can you please merge this into the `upgrade-to-react-admin-v3`-branch so we can continue to work on it together? An beta NPM package for it would be great too.
> 
> BTW Merry christmas

A beta NPM package would be great indeed!

Just started using `react-admin` (so v3) and want to use `react-admin-firebase` as well. Looks like the best Firebase provider for react-admin 👌🏻. However this v3 support is quite vital I think.

If a beta package would be released I could use it and test it. Looking to contribute to this already good and promising package 💪🏻.

**Comment by dhstack** [comment]
Also looking to use this package for react-admin v3. I agree this looks like the most promising package for using Firebase with react-admin. Happy to help test!

**Comment by LaszloDev** [comment]
I added the needed `/dist`-files and pushed them to the `upgrade-to-react-admin-v3`-branch to have a working version. Please try it by linking directly to the github repo branch as package for now via:

`npm install` or `yarn add github:benwinding/react-admin-firebase#upgrade-to-react-admin-v3`

@benwinding has to publish a (beta) package to npm so it can be installed via npm

**Comment by LaszloDev** [comment]
@simonbuerger  thanks again for your work.
I was not able to change the target branch for your pull request to the local upgrade-to-react-admin-v3, so I guess we have to create a new pull request so we can work together on finalizing it, as I would like to make some more changes, at least regards the readme before merging it to the master. Please check if you can change the target branch, otherwise I would close this pull request and open a new one.

**Comment by dhstack** [comment]
@LaszloDev This is awesome, thanks! I was able to install and test with the command `npm install --save github:benwinding/react-admin-firebase#upgrade-to-react-admin-v3` 

I tested reading and writing to a test collection in Firebase and it works just fine. Nice work @simonbuerger!

A few notes:
1. The `authProvider` didn't seem to be built into the `dist` so I couldn't test that with a collection only accessible by an authenticated user. Any way to update the `dist` so that can be tested?
1. I find it strange that an empty `options` object is required for FirebaseDataProvider to successfully compile without an error. Is there a way it could default to an empty object or something so you don't have to pass it explicitly like I did: `const dataProvider = FirebaseDataProvider(firebaseConfig, {});`

**Comment by simonbuerger** [comment]
@LaszloDev I see you managed to merge this branch into upgrade-to-react-admin-v3, so you don't need me to update this PR?

**Comment by LaszloDev** [comment]
I merged your changes and If you don’t mind, let’s close this PR.
You can create a new one, targeting the local v3 branch, for more changes regards v3.

**Comment by dhstack** [comment]
I figured out how to test the Google provider login and it works for me!

**Comment by benwinding** [comment]
Hey Guys,

Sorry about the delay on this PR, seems to work pretty well so I've merged this in and deployed to npm under [`version 3.0.0` ](https://www.npmjs.com/package/react-admin-firebase/v/3.0.0) _(starting at 3.0.0 to follow along with react-admin's major versioning)_

Open a new issue if there's any concerns or problems. Thanks again for all your help and contributions, I really do appreciate it.

Kind regards,
Ben

**Pull request merged**
