### PR TITLE
Add await on update doc

### PR DESCRIPTION
**Pull request by gmenti**

### CODE REVIEW

**Comment by benwinding** [comment]
Good spot! Thanks

**Comment by haynzz** [comment]
Is this in any of the recent releases?

**Comment by benwinding** [comment]
Yes it was incorporated late last year, do you have an issue to report?

**Comment by haynzz** [comment]
It just seems to have been reversed at some point. 
At least on the master branch and whatever is 0.3.0 on npm.

**Comment by benwinding** [comment]
Hi @haynzz,
Thanks for bringing that up, yes I seem to have regressed on that. But version `0.3.1` has the correct functionality, which is awaiting the document change before returning the id. 

See here: [40f969](https://github.com/benwinding/react-admin-firebase/blob/40f969f64cf2b569533df834a59e70fa81dba646/src/firebaseDataProvider.ts#L128)

Cheers,
Ben

**Pull request merged**
