### PR TITLE
Fix 123 (Support DocumentReferences)

### PR DESCRIPTION
**Pull request by benwinding**
- Closes issue #123
- Translates DocumentReference objects from firebase documents in/out of the library.

### CODE REVIEW

**Comment by steventilator** [comment]
Hi @benwinding ,

I'm encountering the following error when using it with the `<ReferenceField />` component:

`FirebaseError: [code=invalid-argument]: Invalid document reference. Document references must have an even number of segments, but insurers/insurers/SrTck[*redacted*]y58 has 3`

My code looks like this:

```
<ReferenceField
  source="insurer.___refdocument"
  reference="insurers"
 >
  <TextField source="name" />
</ReferenceField>
```

It looks to me like the `reference` is added to the path under `____refdocument` when building the path. Might it be easier to use `input.id` instead of `input.path` [here](https://github.com/benwinding/react-admin-firebase/pull/127/files#diff-40b2553b6ecc79b96eca0f030e11fd77R34)?

**Comment by woakley5** [comment]
Is there any update on merging this feature in?

**Comment by kristoffer-try** [comment]
Any updates here?

**Comment by benwinding** [comment]
It's not 100% working yet, it appears that translating in and out of `react-admin` is a difficult problem...

I'll put some more time into this next week, appreciate your patience.

**Comment by mul0w** [comment]
Hi there, any updates on this one ?

**Comment by Rbzh** [comment]
Hi ! Any updates on this PR ?

**Comment by Tittoh** [comment]
@benwinding do we have any progress on this?

**Comment by kiptoomm** [comment]
👀

**Comment by Mizaro** [comment]
Hey, 

What is left to merge it? Can I help in any way?

**Comment by benwinding** [comment]
This has been on my mind lately, and I was finally able to finish it 🎉 
Try using `DocumentReferences` in `react-admin-firebase@3.3.1` (when it's finished deploying)

**Comment by Riken-Shah** [comment]
@benwinding thanks a lot dude! That worked.
Really appreciate your work 👏

**Pull request merged**
