### PR TITLE
Filter Query (<List /> permanent filter for query)

### PR DESCRIPTION
**Pull request by LaszloDev**
As discussed here https://github.com/benwinding/react-admin-firebase/issues/20 the package right now does not filter requests on the server but only locally.

### Problem
When working with extended Firebase security rules and user groups, requests can fail as Firebase rejects them when a single document within the collection could potentially not be readable by the requesting user. 

### Solution
The requests to read a collection sent to Firebase needs to have a filter/ query set, which does match the security rules for the collection and requesting user. I implemented this making use of the _react-admin_ native **permanent filter**-prop. Each `<List />` component can now set a _filter_ which is taking in to action when making the request to Firebase.

### Pull Request
I extended _FirebaseClient_ to pass the filters to `tryGetResource()` and _ResourceManager_ to handle them at `RefreshResource()` and `TryGetResourcePromise()`

### Tested:
- Loaded a restricted collection by adding a permanent filter to a **List** (`<List {...props} filter={{ directory_show: true }} />`) which was not possible before because of the set security rules. 

### TODO:
- Test _react-admin_ search
- Test _react-admin_ user filters
- Right now filter is used to make equal ("==") query check, check if others are needed and possible

The code differences got a bit messy as my prettier this some formatting as the line breaks and some quotes.

Please let me know what you think.

### CODE REVIEW

**Comment by LaszloDev** [comment]
My tests regards the user filters showed that they are ending in the same _filter_-Object as the existing permanent filter and there by used the build the query. Of cause this don't work as the user filter should be done locally with `filterArray()`-function of _FirebaseClient_.

So we would need to have a way to separate between a filter, used to build the Firebase query and a local user filter. What do you think about a special key used in the _List_ filter like
```
<List filter={{ firebaseQueryFilter: { state: 'published' }, allOtherFilters: 'foo' }} />
```

`firebaseQueryFilter` can be extracted and forwarded to `tryGetResource()`, then deleted from `param.filter` to use it for the following local filtering.

```
 public async apiGetList(
    resourceName: string,
    params: messageTypes.IParamsGetList
  ): Promise<messageTypes.IResponseGetList> {
    log("apiGetList", { resourceName, params });

    const queryFilter = params.filter.firebaseQueryFilter;
    delete params.filter.firebaseQueryFilter;

    const r = await this.tryGetResource(resourceName, "REFRESH", queryFilter);
    ...
    const filteredData = filterArray(data, params.filter);
    ...
```

**Comment by LaszloDev** [comment]
@benwinding  Any feedback?

**Comment by benwinding** [comment]
Hi @LaszloDev,
Thanks for developing this, looks like a great idea, but I'm still struggling to work out how to use it this.
Would you be able to add an example resource with this feature demonstrated in `src-demo`? Once I can understand how this works, I'd love to merge it and deploy it to npm :+1: 
Cheers,
Ben

**Comment by LaszloDev** [comment]
Hey @benwinding,
your demo does not let me use your demo database, so I don't know whats your data structure.

As from what I can see you have a `/posts`-collection. You will need to do two steps in Firestore for the example to work:

- Please add, to one or more of your `posts`-items, the key `publishing_state='published'`
- and add the following security rule:
```
    match /posts/{postID} {
    	allow read: if resource.data.publishing_state == 'published'
    }
```

This setup is pretty common when you want to only show items of a collection with a specific state. Right now, which the existing code of `react-admin-firebase` and this security rule, it would not be possible to show the data in react-admin, because the full list of collection items is queried.

The changes of this PR, does not allow to set a fixed query per resource, but it instead allows to set query params per `List`-components filter.  As you might want to change the query based on users permissions.

The `filter`-object of a `<List />`-component is able to take a `firebaseQueryFilter`-object which is used to build the Firebase query, and is then removed to not collide which the local filter.

`firebaseQueryFilter: { [key: string]: string }`
The keys and values are used right now to build a simple 'equals'-query: ...where(key, '==', value)
https://firebase.google.com/docs/firestore/query-data/queries#simple_queries

```
 <List
    {...props}
    filters={<PostFilter />}
    filter={{ firebaseQueryFilter: { publishing_state: "published" } }}
  >
...
```

I added this to your `posts.js` in the demo. Hope this helps to better understand how to use it.
Let me know if you need more clarification,
Laszlo

**Comment by LaszloDev** [comment]
Hey @benwinding, can you have a look please?

**Comment by benwinding** [comment]
Hey @LaszloDev,

Apologies for the delay, work has been busy! I've sat down a few times to figure this out, but it's still not entirely clear to me, what is going on...

So what I've done is publish this to NPM under version `0.9.0-beta.0`. So if you please try this version out with you project, and let me know if it works for you:

`yarn add react-admin-firebase@0.9.0-beta.0`

Let me know the results and I look forward to merging the feature in!!

Cheers,
Ben

**Comment by leonzinger** [comment]
Hey @benwinding,

It's working great, thank you!

One issue, when calling dataProvider GET_LIST and not passing filter object it's throwing an exception
`Cannot read property 'collectionQuery' of undefined`
would expect it to ignore the filter if it doesn't exist

**Comment by LaszloDev** [comment]
Thank you @benwinding for providing an NPM package. Didn’t had the time to check yet.

@leonzinger you are right, this should not happen. I will look into it as soon as I can.

**Comment by leonzinger** [comment]
Hey @benwinding,
Another issue I have noticed. After adding the permanent filter, the table pagination indication does not consider that it shows a smaller number of items.
For example, I have only 1 item showing but pagination shows that there are two pages.

**Comment by LaszloDev** [comment]
> Hey @benwinding,
> Another issue I have noticed. After adding the permanent filter, the table pagination indication does not consider that it shows a smaller number of items.
> For example, I have only 1 item showing but pagination shows that I have 17 items.

> One issue, when calling dataProvider GET_LIST and not passing filter object it's throwing an  exception
> Cannot read property 'collectionQuery' of undefined
> would expect it to ignore the filter if it doesn't exist 

Hey @leonzinger, I tried to reproduce your errors, but for me testing it, with a permanent filter set I do see the right count of items showing in the footer, and without a `filter` Im not getting an error. Basically every time you render a list component the `GET_LIST` is triggered.

Could you please post the contents of your renderers List component.?

----------

@benwinding I just realized that I didn't provide any documentation / code samples so I hope this snipped will help to follow up:

```javascript
import React from 'react'
import { List, Datagrid, TextField } from 'react-admin'

const BenefitList = props => {
  let filter = {
    collectionQuery: collection => collection.where('state', '==', 'published'),
  }

  return (
    <List {...props} filter={filter}>
      <Datagrid rowClick="edit">
        <TextField source="name" />
        <TextField source="state" />
      </Datagrid>
    </List>
  )
}

export default BenefitList
```

**Comment by benwinding** [comment]
Hi @LaszloDev,

Thanks for all your hard work and providing the sample code!

I've just published this to npm as another Beta version, test it out and if you're happy with it, I'll merge the PR into master.

`yarn add react-admin-firebase@0.9.0-beta.1`

Cheers,
Ben

**Comment by leonzinger** [comment]
Hi @LaszloDev,

Thank you for the explanation. I was passing an object to filter instead of the collectionQuery function. 
Now it is working properly.
One small question, can I somehow wait for the filter query resolve before it will render? because at the moment it shows the full list for a split of a second and then shows the filtered list.

**Comment by leonzinger** [comment]
On navigation to "show" screen and navigate back, the filter does not apply the rule. A full list appears without the filter

**Comment by leonzinger** [comment]
Thank you for the explanation @LaszloDev  :)

I do need to apply the right security rules to fetch only the items relevant to a user.
I have Added `roles` object as written in this example [Secure data access for users and groups](https://firebase.google.com/docs/firestore/solutions/role-based-access) and added the security rules from their examples.

Would appreciate getting an example that works,
Thanks
Leon

**Comment by LaszloDev** [comment]
@benwinding please merge 🚀

**Comment by benwinding** [comment]
Published as version **react-admin-firebase@0.9.0**

**Pull request merged**
